import { Activity, CheckCircle2, FileInput, ServerCog } from 'lucide-react';
import { requirePrincipal } from '@/lib/ohworks-tenant/auth';
import { readTenantStore, visibleStore } from '@/lib/ohworks-tenant/store';
import { PageHeading } from '../_components/page-heading';

export const dynamic = 'force-dynamic';

export default async function InstrumentPage() {
  const principal = await requirePrincipal();
  const store = visibleStore(await readTenantStore(), principal);
  const instrument = store.instruments[0];
  return <div className="space-y-7"><PageHeading eyebrow="Instrument operations" title="LIAISON XL" description="Configured analyzer workflow for the OHWorks test tenant." /><section className="grid gap-4 lg:grid-cols-3"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><Activity className="h-5 w-5 text-teal-700" /><p className="mt-4 text-sm text-slate-500">Instrument status</p><p className="mt-1 flex items-center gap-2 text-xl font-semibold"><span className="h-2.5 w-2.5 rounded-full bg-emerald-500" /> {instrument.status}</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><ServerCog className="h-5 w-5 text-teal-700" /><p className="mt-4 text-sm text-slate-500">Current worklist</p><p className="mt-1 text-xl font-semibold">{instrument.queueDepth} sample</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><FileInput className="h-5 w-5 text-teal-700" /><p className="mt-4 text-sm text-slate-500">Result channel</p><p className="mt-1 text-xl font-semibold">{instrument.connection}</p></div></section><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-2"><CheckCircle2 className="h-5 w-5 text-emerald-600" /><h2 className="font-semibold">Operational workflow</h2></div><ol className="mt-5 grid gap-4 md:grid-cols-4">{[['1','Worklist','Queued samples are assigned a rack position.'],['2','Analyzer run','The LIAISON XL test workflow produces a result file.'],['3','Result import','Mapped values enter the result review queue.'],['4','Review','Technical review and release remain recorded stages.']].map(([step,title,detail]) => <li key={step} className="rounded-xl bg-slate-50 p-4"><span className="text-xs font-bold text-teal-700">{step}</span><h3 className="mt-2 text-sm font-semibold">{title}</h3><p className="mt-2 text-xs leading-5 text-slate-600">{detail}</p></li>)}</ol><p className="mt-5 rounded-xl border border-slate-200 bg-slate-50 p-3 text-xs text-slate-600">OrchidLive connectivity is not configured in this tenant. Results use the controlled test file channel.</p></section></div>;
}
