import { notFound } from 'next/navigation';
import { CheckCircle2 } from 'lucide-react';
import { requirePrincipal } from '@/lib/ohworks-tenant/auth';
import { hasPermission } from '@/lib/ohworks-tenant/permissions';
import { readTenantStore, visibleStore } from '@/lib/ohworks-tenant/store';

export const dynamic = 'force-dynamic';

export default async function ReportPage({ params }: { params: Promise<{ reportId: string }> }) {
  const principal = await requirePrincipal();
  if (!hasPermission(principal, 'report:read')) notFound();
  const store = visibleStore(await readTenantStore(), principal);
  const { reportId } = await params;
  const sample = store.samples.find((candidate) => candidate.release?.reportId === reportId);
  if (!sample?.release || !sample.review) notFound();
  return <div className="mx-auto max-w-4xl space-y-5"><div className="flex items-center justify-between rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-emerald-900"><div className="flex items-center gap-2"><CheckCircle2 className="h-5 w-5" /><span className="font-semibold">Released report</span></div><span className="font-mono text-sm">{sample.release.reportId}</span></div><article className="rounded-2xl border border-slate-200 bg-white p-8 shadow-sm"><div className="flex flex-col gap-5 border-b border-slate-200 pb-6 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-teal-700">OHWorks Laboratory</p><h1 className="mt-2 text-2xl font-semibold">Laboratory result report</h1></div><div className="text-sm sm:text-right"><p className="font-mono font-semibold">{sample.id}</p><p className="mt-1 text-slate-500">Order {sample.orderId}</p></div></div><dl className="grid gap-4 border-b border-slate-200 py-6 text-sm sm:grid-cols-3"><div><dt className="text-xs uppercase tracking-wide text-slate-400">Subject reference</dt><dd className="mt-1 font-medium">{sample.subjectReference}</dd></div><div><dt className="text-xs uppercase tracking-wide text-slate-400">Specimen</dt><dd className="mt-1 font-medium">{sample.specimen}</dd></div><div><dt className="text-xs uppercase tracking-wide text-slate-400">Panel</dt><dd className="mt-1 font-medium">{sample.panel}</dd></div></dl><table className="mt-6 w-full text-left text-sm"><thead className="border-b border-slate-200 text-xs uppercase tracking-wide text-slate-500"><tr><th className="pb-3">Test</th><th className="pb-3">Result</th><th className="pb-3">Reference</th><th className="pb-3">Flag</th></tr></thead><tbody className="divide-y divide-slate-100">{sample.results.map((result) => <tr key={result.code}><td className="py-4"><p className="font-medium">{result.analyte}</p><p className="text-xs text-slate-500">{result.code}</p></td><td className="py-4 font-semibold">{result.value} {result.units}</td><td className="py-4">{result.reference}</td><td className="py-4">{result.flag}</td></tr>)}</tbody></table><div className="mt-8 grid gap-5 border-t border-slate-200 pt-6 text-sm sm:grid-cols-2"><div><p className="text-xs uppercase tracking-wide text-slate-400">Technical review</p><p className="mt-1 font-medium">{sample.review.actor}</p><p className="mt-1 text-xs text-slate-500">{new Date(sample.review.at).toLocaleString('en-GB', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'UTC' })} UTC</p></div><div><p className="text-xs uppercase tracking-wide text-slate-400">Release approval</p><p className="mt-1 font-medium">{sample.release.actor}</p><p className="mt-1 text-xs text-slate-500">{new Date(sample.release.at).toLocaleString('en-GB', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'UTC' })} UTC</p></div></div></article></div>;
}
