import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import test from 'node:test';
import { classifyFile } from '../../scripts/lib/provenance-classifier.mjs';

const root = fileURLToPath(new URL('../../', import.meta.url));
const cli = path.join(root, 'scripts/provenance-inventory.mjs');
const fixture = path.join(root, 'tests/fixtures/provenance-sample');
const run = (...args) => spawnSync(process.execPath, [cli, ...args], { cwd: root, encoding: 'utf8' });
const classify = (relPath, firstLineText = 'Synthetic text') => classifyFile({ relPath, ext: path.extname(relPath), sizeBytes: 20, firstLineText });
const expect = (result, category, riskLevel) => {
  assert.equal(result.category, category);
  assert.equal(result.riskLevel, riskLevel);
  assert.ok(result.reasons.length > 0);
};
function temporary(t) {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'provenance-test-'));
  t.after(() => fs.rmSync(directory, { recursive: true, force: true }));
  return directory;
}

test('attribution takes precedence over own-writing paths and never echoes text', () => {
  for (const marker of ['Copyright', '©', 'ALL RIGHTS RESERVED', 'Licensed under']) {
    for (const ext of ['md', 'txt']) {
      const result = classify(`notes/test.${ext}`, `${marker} SECRET_SAMPLE`);
      expect(result, 'third-party-document', 'high');
      assert.ok(!JSON.stringify(result).includes('SECRET_SAMPLE'));
    }
  }
});

test('sensitive path substrings override every other risk, case-insensitively', () => {
  for (const marker of ['INVOICE', 'Contract', 'NDA', 'license']) {
    for (const name of ['notes/a.md', 'a.psd', 'a.json', 'exports/a.csv', 'a.pdf', 'a.blob']) {
      assert.equal(classify(`${marker}/${name}`).riskLevel, 'high');
    }
    expect(classify(`${marker}/a.bin`, null), 'unknown', 'high');
  }
});

test('media and stock-photo markers', () => {
  for (const ext of ['psd', 'ai', 'indd', 'png', 'jpg', 'jpeg', 'gif', 'svg', 'webp', 'mp3', 'wav', 'mp4', 'mov']) {
    expect(classify(`photo.${ext}`), 'media-asset', 'medium');
  }
  expect(classify('STOCK-PHOTO.blob'), 'media-asset', 'medium');
});

test('generated exports by path and first-line marker', () => {
  for (const name of ['exports/table.csv', 'export.json', 'data-export.csv']) expect(classify(name), 'generated-export', 'medium');
  for (const marker of ['Generated by', 'Auto-generated', 'Automatically generated']) expect(classify('notes/a.md', marker), 'generated-export', 'medium');
});

test('own-writing requires both editable extension and draft/notes/journal path', () => {
  for (const marker of ['DRAFT', 'Notes', 'journal']) {
    for (const ext of ['ts', 'js', 'py', 'json', 'md', 'txt']) expect(classify(`${marker}/a.${ext}`), 'own-writing', 'low');
  }
  expect(classify('notes/a.blob'), 'unknown', 'unknown');
  expect(classify('notes/a.psd'), 'media-asset', 'medium');
  expect(classify('notes\\a.MD'), 'own-writing', 'low');
});

test('source/config and document extensions are conservative', () => {
  for (const ext of ['ts', 'js', 'mjs', 'cjs', 'tsx', 'jsx', 'py', 'json', 'yaml', 'yml', 'toml', 'ini']) expect(classify(`a.${ext}`), 'code-or-config', 'medium');
  for (const ext of ['pdf', 'doc', 'docx', 'ppt', 'pptx', 'epub']) expect(classify(`a.${ext}`), 'third-party-document', 'medium');
});

test('unknown is deliberate for unmatched and unavailable samples', () => {
  for (const name of ['a', 'a.blob', 'a.md', 'a.txt']) expect(classify(name), 'unknown', 'unknown');
  expect(classify('notes/a.md', null), 'unknown', 'unknown');
  expect(classifyFile(), 'unknown', 'unknown');
  assert.deepEqual(classifyFile({ relPath: 'a', ext: '', sizeBytes: 0, firstLineText: '' }), classifyFile({ relPath: 'a', ext: '', sizeBytes: 999, firstLineText: '' }));
});

test('fixture inventory appears exactly once with known summary and no contents', (t) => {
  const output = path.join(temporary(t), 'report.json');
  const result = run('tests/fixtures/provenance-sample', '--out', output);
  assert.equal(result.status, 0, result.stderr);
  assert.equal(result.stdout, '');
  const report = JSON.parse(fs.readFileSync(output, 'utf8'));
  assert.deepEqual(report.summary, { low: 2, medium: 4, high: 2, unknown: 1 });
  assert.deepEqual(report.files.map(file => file.relPath).sort(), ['attributed.md', 'config.json', 'draft-notes.md', 'exports/table.csv', 'handout.docx', 'invoice-2023.pdf', 'mystery.blob', 'notes/idea.py', 'photo.psd'].sort());
  for (const file of report.files) {
    assert.equal(file.sizeBytes, fs.statSync(path.join(fixture, file.relPath)).size);
    assert.deepEqual(Object.keys(file).sort(), ['relPath', 'sizeBytes', 'category', 'riskLevel', 'reasons'].sort());
  }
  assert.ok(!JSON.stringify(report).includes('Example Corp'));
  assert.deepEqual(JSON.parse(run(fixture).stdout), report);
  assert.equal(run(fixture, '--out', output).status, 1);
  assert.deepEqual(JSON.parse(fs.readFileSync(output, 'utf8')), report);
});

test('missing folder and malformed arguments fail with usage and no report', () => {
  for (const args of [[], ['--out', 'report.json'], [fixture, '--bad'], [fixture, '--out']]) {
    const result = run(...args);
    assert.equal(result.status, 1);
    assert.match(result.stderr, /Usage:/);
    assert.equal(result.stdout, '');
  }
});

test('skips symlink files/directories and handles binary samples and bounded reads', (t) => {
  const temp = temporary(t);
  const input = path.join(temp, 'input');
  fs.mkdirSync(input);
  fs.writeFileSync(path.join(temp, 'outside.txt'), 'Copyright SECRET_OUTSIDE');
  fs.symlinkSync(path.join(temp, 'outside.txt'), path.join(input, 'linked.md'));
  fs.symlinkSync(temp, path.join(input, 'linked-directory'));
  fs.writeFileSync(path.join(input, 'draft.md'), Buffer.from([0, 1, 2]));
  fs.writeFileSync(path.join(input, 'invalid.md'), Buffer.from([0xff, 0xfe]));
  fs.writeFileSync(path.join(input, 'notes-long.md'), `${'a'.repeat(200)}\u0000SECRET_AFTER_LIMIT`);
  const result = run(input);
  assert.equal(result.status, 0, result.stderr);
  const report = JSON.parse(result.stdout);
  assert.deepEqual(report.files.map(file => file.relPath), ['draft.md', 'invalid.md', 'notes-long.md']);
  assert.deepEqual(report.summary, { low: 1, medium: 0, high: 0, unknown: 2 });
  assert.ok(!result.stdout.includes('SECRET'));
  assert.equal(run(path.join(input, 'linked-directory')).status, 1);
  assert.equal(run(path.join(temp, 'missing')).status, 1);
  assert.equal(run(path.join(input, 'notes-long.md')).status, 1);
});

test('unreadable files do not crash the walk', (t) => {
  if (process.getuid?.() === 0) return t.skip('Root bypasses file permission restrictions');
  const input = temporary(t);
  const file = path.join(input, 'draft.md');
  fs.writeFileSync(file, 'Synthetic inaccessible text');
  fs.chmodSync(file, 0);
  t.after(() => { if (fs.existsSync(file)) fs.chmodSync(file, 0o600); });
  const result = run(input);
  assert.equal(result.status, 0, result.stderr);
  expect(JSON.parse(result.stdout).files[0], 'unknown', 'unknown');
  assert.equal(JSON.parse(result.stdout).files[0].sizeBytes, Buffer.byteLength('Synthetic inaccessible text'));
});
